### ISSUE TITLE
Phaxio callback

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#101]
I have the appropriate callback setup in the Phaxio system per this template:
https://domain/nosh/phaxio/1

However, this function appears to be failing as I do not receive a fax within NOSH and the Phaxio web interface reports that the callback is not going through.

Out of curiosity I entered the callback URL into a web browser to see what would happen and I received a message that might be an error (or I suppose it might just be there because it's not technically a visit-able web address). I wanted to run it by you to see if there might be an error here or not.
Here is the message I got when visiting the callback URL:

![callbackurl](https://user-images.githubusercontent.com/26801488/32586740-60fd897c-c4fc-11e7-9c1b-b91ecdbb29d3.png)

**Comment by shihjay2** [comment]
The reason you see the error is that when you call the URL on the browser, it is a GET request instead of a POST request that NOSH is looking for - which Phaxio is supposed to send out.  I've made a few changes in commit ebf230835896b370ddcddae94e17fe0e0401c975.  You can try it again to see if it works.

**Comment by rumsant** [comment]
Not working for me, but it's probably something on my end.
I'm going to close this and just use an email for a callback.
