### ISSUE TITLE
php7?

### ISSUE THREAD

**Issue by tloudon** [shihjay2/nosh2#110]
Hello,

Wondering if you have looked at php7 support at all.  It looks like laravel supports php7 ("PHP >= 7.1.3
").  PHP 5.6 is [EOL for security updates in December](http://php.net/supported-versions.php).

I'll try to set up a new box w/ php7 and try running one of the compatibility checkers, but not being familiar w/ the app is going to make this a little harder.

Thanks!

**Comment by shihjay2** [comment]
Actually if you inspect the droplet-nosh-install.sh code, php 7.2 is installed as default.  The dependencies in composer.json also mandates it even though the minimum version for php is 5.5 just to ensure backwards compatibility for some dependencies.  Hope that makes sense.

**Comment by tloudon** [comment]
Yeah that does make sense.  What's the difference between the droplet-install.sh and the install.sh?  Also, is the FTP server required?  I assume I can sub nginx for apache, yeah?  Sorry to pepper you w/ questions.  Maybe I can send a PR for the readme (there are references to the old repo anyway)?

Thanks!

**Comment by shihjay2** [comment]
The droplet install is an automated install script for the patient centered longitudinal health record project that NOSH is a part of called [HIE of One](https://github.com/shihjay2/hieofone-as) for cloud server/virtual machine deployments. Yes, a PR would be great to update the readme (I've been a one-man project since 2010) as I've been busy working on the above patient centered longitudinal health record project.

**Comment by tloudon** [comment]
OK, I will send a PR later this week on the readme.

I think I've got it largely up and running (didn't hook up fax, etc).  Is there a way to import patients into the demographics table?  It seems like this would be a common first step.  I'll start writing down these getting started tasks (eg, looks like a google oauth is required; make sure outbound mail is configured, need to add providers, visit types, etc).  Do you want me to create a new issue or just have them here?

Thanks!
