### ISSUE TITLE
Regarding prescribing drugs

### ISSUE THREAD

**Issue by mybharathraj** [shihjay2/nosh2#111]
Hi. Its a great pleasure to use this software. I have tried the demo and this is just amazing. It would have been very nice if there was an option of prescribing many drugs in a single sheet when we take prints of the prescription. I could only take prints of only one drug. Can you make it possible to add multiple drugs in a list and take print of that?
Will be waiting for your answer. Thank you.

**Comment by shihjay2** [comment]
Addressed in commit f7c3883af65e78108eb274b8333601a724f371a6.  When you save a medication for prescribing, under Action Under Save - set to Add to Print Queue, Combined in One Page or Add to Fax Queue, Combined in One Page.   You can mix prescriptions that require single or combined in a Print Queue as you'll probably need the flexibility for medications that are controlled substances to be on a single page instead of a combined prescription.  Due to limitations of paper size and layout, only 3 prescriptions can be set in one page; it will generate multiple pages if you exceed that amount in the queue.

**Comment by mybharathraj** [comment]
Thank you very much. I get it. But is it possible to make drug list longer in single sheet. I can see lot of space underutilized. I was thinking it would have been best if there was option of changing the format of prescription sheet. Idea of handing over a single prescription sheet to patient is less confusing than giving multiple sheets.

**Comment by shihjay2** [comment]
Reformatted prescription page and now can hold up to 5 prescriptions in one page,  Commit 014c81ffbe0a3dd6cf3fc4b197828a5de55eab9f

**Comment by mybharathraj** [comment]
Thank you very much..
