### ISSUE TITLE
Installation on common webhosting

### ISSUE THREAD

**Issue by kelesi** [shihjay2/nosh2#123]
It would be nice to make this possible to install on 3rd party web hosting server, where you don't have usually shell access and if you do, you never get root access.

**Comment by shihjay2** [comment]
If you are a US physician, all common webhosting solutions will not be HIPAA compliant so that is not an option.  However, if you're country of practice does not have regulations over the security and safeguarding of patient-related health care data, it would depend on the webhosting server itself to be able to install NOSH.  Because NOSH, by design, is dependent on a database (it uses MariaDB) which most webhosting services limit access to; and there are specific dependencies (like PHP) that most webhosting services may not have, it would be difficult to deploy NOSH in these types of environments.

**Comment by shihjay2** [comment]
I will need more information from you regarding the type of web hosting
server you use and how to get around shell scripting.  All of the
installers scripts for NOSH require at least shell access.
