### ISSUE TITLE
Debugging nosh 

### ISSUE THREAD

**Issue by mohammadmahboubeh** [shihjay2/nosh2#172]
Hi there!
How can I debug the project using vs code or phpstorm?

Thanks

**Comment by shihjay2** [comment]
Make sure you ENV file as these settings: 
`APP_ENV=local` and `APP_DEBUG=true`

**Comment by mohammadmahboubeh** [comment]
Yeah there configured as mentioned. I mean how can I debug from docker container?

thanks from your prompt reply

**Comment by shihjay2** [comment]
If you run NOSH from docker-compose, just run it without the daemon option (docker-compose up) and you can see all commands and network functions between each container (web server, database) in real time; is that what you mean?

**Comment by mohammadmahboubeh** [comment]
If I want to debug and develop it like changing the name of some fields to fit into vet clinic, I should use let say vs code to see the change in real time

**Comment by shihjay2** [comment]
Debugging using docker-nosh is probably not the best way to do this if you want to test out new fields, UI, PHP changes.  Docker images are ephemeral and any changes you make won't be saved and it's hard to edit changes directly in a Docker image since it's using a very sparse Alpine Linux build.  Probably best to fork the NOSH2 repo and install it manually with Apache as the web server my MariaDB or MySQL as the database; and work off your local development machine to see changes in real time.

**Comment by mohammadmahboubeh** [comment]
I see. Tried many times to install it locally using Apache but too much errors got, then you advise me to use docker. If is it possible to send all the dependency must have or the steps of installation it would be much appreciate it.
Here is my email: mahboubeh1991@outlook.com 

Thanks Dr.shihjay
