### ISSUE TITLE
Acess to /nosh folder on apache server

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#42]
This has happened to me in the past, but I've just done a reinstall because I was working on other problems with the install:

After NOSH working fine, at some point I vagrant halt, and then vagrant up at some point later on. When I try to access either the local-ip/nosh or the domain/nosh (both of which worked find previously) I get taken to a page that says "Forbidden - You don't have permission to access /nosh on this server.

I think that each time this has happened the only thing that has changed has been a change in the local ip address assigned to the ubuntu/xenial64 virtual machine.

I'm guessing that there is a file I have to modify somewhere, or something like that, but I just don't know what or where it is.

**Comment by shihjay2** [comment]
You can try a static IP address respective to your router - make sure you set the IP to fall outside of what is assigned through DHCP (it's a range of addresses - you can shorten the range, last 3 numbers) so that you can assign a number.  Some routers allow you to assign a static IP based on a MAC address too so that's one method.  Another method:

In Vagrantfile
add the ip option after "public_network" and choose an ip that is outside the range for DHCP by router
`config.vm.network "public_network", ip: "192.168.0.17"`

Save, and `vagrant reload`

**Comment by shihjay2** [comment]
Will move this issue to nosh-in-the-box project as topic pertains more to that project than to nosh2

**Comment by shihjay2** [comment]
This issue was moved to shihjay2/nosh-in-a-box#1
