### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#58]
If I may ask 3 questions:

1) Regarding the backing up of Nosh information, is the best route to export the
entire database as a .sql file?

If so, then I assume that if one ever needed to restore a backup, the route would
be to import the .sql file to the Nosh database via mysqladmin?
And then this would restore all of the information (patients, encounters, schedule,
etc.) into the Nosh system?

I'm just trying to work toward implementing this, so I need to make sure I  understand
how to recover all my data in a worst case scenario.

2) Would it make sense for me to set up my own textbelt system to connect to Nosh, so
that it would be an email address I owned that was sending the reminders? Or would this
be needlessly complicated? I'm guessing needlessly complicated based on the fact that my
technical knowledge prevents me from really understanding how I would even set up textbelt
on my own. Thought I'd ask out of curiosity.

3) Regarding templates, what are the stars for? I seem to remember that clicking on them
would pop up a message about something.

Thank you.

**Comment by shihjay2** [comment]
For backup, NOSH automatically creates backups once a month in your system.  In admin login, you can restore a backup at a given time if you wish.  The only thing that is not backed up is the documents that are uploaded into the system.  They are saved in the /noshdocuments/<patient_id>/ folders.

You can certainly create your own textbelt system but then you'll also need to modify the code to point the URL.  If you're interested in doing that I can update NOSH so that you can manually assign the URL instead of it being hardcoded right now.  Here's a good link to start https://lowendbox.com/blog/how-to-send-sms-messages-from-your-vps-using-textbelt/

The stars are for automatically copying template items selected as default.  So if you're in the template items list (not groups which is the first level when you click on a text box) having the item starred (it would only be text - not items that require input, checkboxes, dropdowns, or radio buttons) would mean it's set as default text.  When the star is filled it's default.  In the template group list, click on the star on the left hand side will pull in all items that are starred in the item list for that group.  So one could make a template text that is a very long text if they want, star it, and in the group, they can quickly pull in that information into the textbox with that defaulted text.  Hope that makes sense.

**Comment by rumsant** [comment]
Great. I'll check that link and see if I can get a handle on it.

And I think I get the star function.

Thanks again.

**Comment by rumsant** [comment]
Well, I got the textbelt server up and running (Easter miracle).

I'll take you up on your earlier offer of updating NOSH so that I can manually assign the URL instead of it being hardcoded, if that is still an option.

**Comment by shihjay2** [comment]
I'll let you know when it's updated - probably early next week.  You can manually change the URL in line 15175 in /noshdocuments/nosh2/app/Http/Controllers/Controller.php and change $url = "http://cloud.noshchartingsystem.com:9090/text"; to the corresponding one.

**Comment by rumsant** [comment]
Great. Thank you.

One last thing: There is a local carrier with an SMS gateway that is not included in the textbelt "carriers.js" file--If I follow the same formatting, I should be able to add that carrier to the file, right?

**Comment by shihjay2** [comment]
I'm going to assume that you should be able to add carriers in that file.  BTW you can `update_system` again since I have updated the code so you can set your own TextBelt server.
