### ISSUE TITLE
Diagnosis pointer not available in specific scenario

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#66]
Here's the scenario:
Host machine running Nosh-in-a-box has internet access so that online features like appt reminders, etc. work.
Additional computers in the office are not allowed internet access. They have this blocked via router settings. These computers are able to access Nosh-in-a-box just fine over the LAN using the local IP address of Nosh-in-a-box.
The only thing that doesn't seem to work is that the Diagnosis Pointer dropdown box does not appear at all for computers that are denied internet access. If I enable internet access for those computers, the Diagnosis Pointer dropdown box appears as normal.
Just wondering if this is fixable or if it is a limitation of the way the program needs to function.

**Comment by shihjay2** [comment]
Looking into this, I don't believe it is fixable as there are several javascript dependencies and fonts that require online access; otherwise, multiple errors will occur and stop any subsequent javascript calls (even if it is for internal purposes) to stop prematurely hence, the drop down box being empty.

**Comment by shihjay2** [comment]
Just wondering if you could give me a screenshot of the page where you have the dropdown box for diagnosis pointer with a view of the console as well  - I'm trying to test out what happens when I use NOSH 2.0 without internet access and the only issues I get are primarily fonts being changed and a missing spinning gif but I'm not pulling up any other errors or missing functionality with the dropdown yet; I'm curious what you're getting on your end.

**Comment by shihjay2** [comment]
I moved all the Google fonts internally - I think those the only things that make a call using the internet; commit a8e259f8878b6acd2f9a3a431cf4a748f7724713 updated

**Comment by rumsant** [comment]
I just did a quick check after updating and it appears that you have fixed my problem.
I can still get you a screenshot of the page with console if you'd like, but I'm assuming
that is of no need to you now. If you want it, let me know.

Also, I now see that some of the outlines around text entry boxes in various sections of
an encounter are colored red. I don't recall having seen this before. What does this denote?
