### ISSUE TITLE
Schedule search

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#81]
If a patient were to call and ask when their next appointment is scheduled for, how would you know?

I don't believe there is any way to search for a specific patient's next appointment.

If this is correct, I think it would be useful to be able to search for scheduled appointment by patient name or something functionally equivalent.

**Comment by shihjay2** [comment]
This was a feature I that existed in NOSH 1 that I took out of NOSH 2 until I found a good place for it - I think the timeline view was the best and so you'll see it first thing when you search and select the patient or when you click on the patient's name on the left side menu.  Fixed in commit 9116b1463830f0dcab15ce18a4a8fb510f6eb6c1

**Comment by rumsant** [comment]
I agree. That seems easier than a separate schedule search function. Very nice.
