### ISSUE TITLE
[Suggestion] Return to non-blank page after sending fax

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#99]
After sending a fax in NOSH, I am directed to a blank white page. I can easily modify the address bar to bring myself back to NOSH, but it would be more efficient to return directly to the fax or main page.

Unrelated: With regards to Phaxio integration with NOSH, is it possible to receive faxes from w/in the NOSH interface?

**Comment by shihjay2** [comment]
Fixed in commit 737bb7fa68ee3d3be5eff4185acb18413c405378 and 1e28c9f2e5f7d9bd0031e7b1e27ef129ef3b443e.  

For receiving faxes, make sure in the Phaxio web console that you have a callback URL entered as such:
`https://<your domain>/nosh/phaxio/1`
1 is your practice_id which is usually the case if you're installing NOSH on your own.

Go to [this link for more information](https://www.phaxio.com/docs/api/v1/receive/receiveCallback)

When this is set and when you receive a fax to your Phaxio number, then the file will show up in the Messaging then Faxes (in the dropdown) page.
